# Generated by Django 3.2.10 on 2022-08-14 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_written_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewed_book',
            name='written_by',
        ),
        migrations.AlterField(
            model_name='book',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
