# Generated by Django 3.2.10 on 2022-08-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220816_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
