# Generated by Django 3.2.10 on 2022-08-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_author_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
