# Generated by Django 3.2.10 on 2022-08-17 13:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220816_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
