version: '3'

services:
  test_db:
    image: postgres:latest
    container_name: test_db
    volumes:
      - test_volume:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  test_volume:
    external: true

